### PR TITLE
new-string

### PR DESCRIPTION
**Pull request by GarryFlemings**
## Description
Intended:  Change Settings > Tools > MJML Settings > Preview > Builtin rendering ...
from: `Disable to use custom rendering script`
to: `Disable custom rendering script`

WebStorm found only one instance of the subject string in the directory. I took a chance that I could make this change for you, should you want it.

### CODE REVIEW

**Comment by timo-reymann** [comment]
I would say with *Enable* insted of *Disable* its a good improvement 👍 

Otherwise the explanation would be the opposite of the effect.

**Comment by GarryFlemings** [comment]
Yup yup.

Maybe make that even more explicit by using two radio buttons for "builtin rendering ..." and "Path to ..."?

**Comment by timo-reymann** [comment]
tbh i have not thought about different ui approaches. 

But thats a good idea, maybe an combox like JetBrains is using for e. g. maven or python interpreter: https://jetbrains.github.io/ui/controls/combo_box/#when-to-use

The radio button might not be a good choice according to the docs:
https://jetbrains.github.io/ui/controls/radio_button/

**Comment by GarryFlemings** [comment]
Wait. `Disable to use custom rendering script` means `Disable builtin rendering script ... to use custom ...`.
Seems right?
And wordy. No suggestion to do that.

My proposal reversed the meaning. Unintentional. I take back that suggestion.

Right about radio buttons.

(blush) I take it all back. No suggestion for change here.

I'd close this, but I'll let you read it first. Or you can close it.

**Pull request closed without merging**
